# Generated by Django 5.0.6 on 2024-06-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navsysMain", "0002_rename_operationrecord_record_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="ip_address",
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="last_connection_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="mac_address",
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="sn",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
