# Generated by Django 5.0.6 on 2024-06-23 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navsysMain", "0003_alter_device_ip_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="last_connection_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="device",
            name="mac_address",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="sn",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
