# Generated by Django 5.0.6 on 2024-06-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navsysMain", "0004_alter_device_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="rfid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="rfid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
