# Generated by Django 5.0.6 on 2024-06-23 08:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("navsysMain", "0007_alter_device_options_alter_environment_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={"verbose_name": "设备", "verbose_name_plural": "设备"},
        ),
        migrations.AlterModelOptions(
            name="environment",
            options={"verbose_name": "环境", "verbose_name_plural": "环境"},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "物品", "verbose_name_plural": "物品"},
        ),
        migrations.AlterModelOptions(
            name="record",
            options={"verbose_name": "记录", "verbose_name_plural": "记录"},
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={"verbose_name": "仓库", "verbose_name_plural": "仓库"},
        ),
    ]
