# Generated by Django 5.0.6 on 2024-06-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navsysMain", "0008_alter_device_options_alter_environment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="name",
            field=models.CharField(max_length=100, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="remark",
            field=models.TextField(blank=True, verbose_name="备注"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="rfid",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="RFID"
            ),
        ),
    ]
