# Generated by Django 5.0.6 on 2024-06-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navsysMain", "0010_alter_device_sn_alter_environment_humidity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="navsysMain.warehouse",
                verbose_name="位置",
            ),
        ),
    ]
