# Generated by Django 5.0.6 on 2024-06-27 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("navsysMain", "0011_alter_device_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Threshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="最高温度",
                    ),
                ),
                (
                    "max_humidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="最高湿度",
                    ),
                ),
                (
                    "max_light",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="最高光照",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="navsysMain.device",
                        verbose_name="设备名",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="navsysMain.warehouse",
                        verbose_name="位置",
                    ),
                ),
            ],
            options={
                "verbose_name": "阈值",
                "verbose_name_plural": "阈值",
            },
        ),
    ]
