# Generated by Django 5.0.6 on 2024-06-27 12:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("navsysMain", "0012_threshold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="threshold",
            name="location",
        ),
    ]
